# Generated by Django 4.1.5 on 2023-01-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='invoice',
            field=models.IntegerField(default=0),
        ),
    ]
